name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pytest
        working-directory: Oblig2Testing  # Erstatt 'path/to/your/project' med den faktiske stien til din prosjektmappen

      - name: Run tests
        run: |
          pytest tests/test_isLeapYear.py
        working-directory: Oblig2Testing/tests  # Erstatt 'path/to/your/project' med den faktiske stien til testmappen
